### PR TITLE
Reconfigure db

### PR DESCRIPTION
**Pull request by doinalangille**
# Description

Copy the notebook 'copy_data' into the folder, and update the documentation with the usage of autogenerated columns

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, reviewed and ready to merge

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by bendevera** [comment]
Do we want to remove `copy_data.ipynb` from root directory?

**Comment by doinalangille** [comment]
> Do we want to remove `copy_data.ipynb` from root directory?

yes

**Comment by bendevera** [comment]
okay I think `git rm copy_data.ipynb` needs to be run in the root directory to remove it from the branch

**Comment by doinalangille** [comment]
> okay I think `git rm copy_data.ipynb` needs to be run in the root directory to remove the one from the root directory of the branch

ok, done. Thanks

**Pull request closed without merging**
